### ISSUE TITLE
Create a login page for internal users

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#471]
### Description
We need to separate the username/password login from the SPID login. Username password login should be accessible only for internal network users, while SPID login should be the unique login available for external users. 

For this reasons we need to : 
- [x] Hide from the current login form in MapStore, the part of "Username/Password" login, allowing only SPID login. 
- [ ] Create a separate page in MapStore ( a separate html file named `internal-login.html` )
    - [x] The page should contain the string "Accesso riservato agli utenti interni" (for the IT translation) and show a prompt for login with username and password, interacting with the standard mapstore login service, as the current login service does.
    - [x] In case of failure, I see an error on the page.
    - [x] If the login has success, the page:
        - [x] save in session storage the information in the same way that MapStore expect
        - [x] Redirect to the MapStore home page (something like `window.location.href = './'` ), so the user logged in can access to mapstore.
    - [x] The page above need to be included in the final build ( verify that it is included in `war` file and working in a final version of the application)
- [ ] #481

### Acceptance Criteria - AC

- As an external user, I can login only via SPID using the form in MapStore. No other login is visible in the form of login in MapStore. I don't have access to the page of internal login below.
- As an internal user I know the URL for the internal login. `/mapstore/internal-login.html`. Opening that page I can login using my credentials (mapstore or ldap) and be redirected to MapStore logged in.

#### Suggestion

I suggest to do a minimal web page with no JS libs, if possible, so you can reduce at minimal the dependencies and the code to write. 

Something like this (taken on internet) should be enough:

```html
<div class="container">

        <div class="intro-text">
            <h1>Login</h1>
            <p>Accesso riservato agli utenti interni</p>
        </div>
        <div class="inputs">
            <div class="input">
                <input type="text" name="username" id="username" required/>
                <label for="username">
                    Username
                </label>
            </div>
            <div class="input">
                <input type="password" name="password" id="password" required/>
                <label for="password">
                    Password
                </label>
            </div>
        </div>
        <button>Sign in</button>

    </div>
```

```css
*{
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}
.container{
    width: 320px;
    height: 480px;
    background: #fff;
    box-shadow: 0 10px 15px rgba(179, 179, 179, 0.7);
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
    border-radius: 7px;
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
    padding: 1rem;
}

.container h2{
    color: #0A66C3;
    font-size: 1.6rem;
}

.container h2 i{
    font-size: 1.8rem;
    padding-left: 0.1rem;
}
.intro-text p{
    font-size: 1.8rem;
    padding-top: 0.3rem;
}

.input{
    position: relative;
    width: 100%;
    height: 50px;
    margin-bottom: 0.7rem;
}

.input input{
    width: 100%;
    height: 50px;
    padding-top: 1.1rem;
    padding-left: 9px;
    outline: none;
    border: 1px solid #8c8c8c;
    border-radius: 3px;
    transition: 0.2s;
}

.input label{
    position: absolute;
    top: 30%;
    left: 10px;
    font-size: 1.1rem;
    color: #8c8c8c;
    transition: 0.2s;
}

.input input:focus ~ label, .input input:valid ~ label{
    top: 10%;
    font-size: 0.8rem;
    color: #000;
} 

.input input:focus{
    border-width: 2px;
    border-color: #0A66C3;
}

.forgot-pass-link{
    width: 140px;
    padding: 0.2rem;
    text-align: center;
    text-decoration: none;
    font-weight: bolder;
    color: #0A66C3;
    transition: 0.3s;
    border-radius: 12px;
}

.forgot-pass-link:hover{
    background: rgba(10, 102, 195, 0.3);
}

button{
    height: 50px;
    background: #0A66C3;
    outline: none;
    border: none;
    border-radius: 30px;
    color: #fff;
    font-size: 1rem;
    font-weight: bolder;
}

.join-link{
    text-align: center;
}

.join-link a{
    text-decoration: none;
    font-weight: bolder;
    color: #0A66C3;
}
```
Result:
![image](https://user-images.githubusercontent.com/1279510/134150721-26bcfa3c-60b1-4935-bfe6-58e93f7f0985.png)

#### Can not create a react-router page
We can not create a page with a `react-router` path because the part after the `#` is not sent to the web server by the browser, so it could be impossible to deny the access to this page by web-server.
we can write 
```
<Location mapstore/internal-login.html>
   Deny ...
</Location>
```
But not: 
```
<Location mapstore/#internal-login>
   Deny ...
</Location>
```

Sources:
- https://serverfault.com/questions/972910/apache-redirect-to-same-path-but-with-a-fragment
- https://stackoverflow.com/questions/3408664/how-to-detect-and-redirect-from-url-with-anchor-using-mod-rewrite-htaccess
